### ||| POSTBEAR |||
### Global Variables
@var3 = world
@var1 = 01010101
@var2 = hello

### list users
GET https://fooapi.com/api/users?param1=value1&param2=value2
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: application/json
Accept: */*

### edit todo
PATCH https://fooapi.com/api/todos/7
Connection: keep-alive
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate, br

{"todo":"Do homework"}

### delete song
DELETE https://fooapi.com/api/songs/34
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: application/json

### invalid request
INFO https://fooapi.com/api/movies
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

